import { Commissioner } from "next/font/google";
import "./globals.css";
import Aside from "@/components/header/aside";
import Nav from "@/components/header/nav";
import MainContainerShadow from "@/components/mainContainerShadow/mainContainerShadow";

const font = Commissioner({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={font.className}>
        <Aside />
        <Nav />
        <MainContainerShadow>{children}</MainContainerShadow>
      </body>
    </html>
  );
}
