import { Inter } from "next/font/google";
import "./globals.css";
import { headers } from "next/headers";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const headersList = headers();
  // read the custom x-url header
  const header_url = headersList.get("x-url") || "";
  console.log(header_url);
  return (
    <html lang="en">
      <body className={inter.className}>
        we are on {header_url.replace("http://localhost:3000", "")}
        {children}
      </body>
    </html>
  );
}
